`import "acorn.shell.js"`
`import "spliced.shell.js"`
`import "collection.shell.js"`
`import "link.shell.js"`
`import "text.shell.js"`
`import "doc.shell.js"`
`import "pdflink.shell.js"`
`import "videolink.shell.js"`
`import "empty.shell.js"`
`import "random.shell.js"`
`import "vimeo.shell.js"`
`import "gallery.shell.js"`
`import "registry"`
`import "youtube.shell.js"`
`import "highlights_shell"`
`import "shell"`
`import "imagelink.shell.js"`
`import "slideshow.shell.js"`
